# Generated by Django 4.2.3 on 2023-07-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_remove_post_body_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
