# Generated by Django 4.2.3 on 2023-07-28 10:55

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0003_remove_post_tags_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(to='author.author'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='SocialMediaSharing',
        ),
    ]
